version: '3.9'
services:
  webb-wallpaper:
    container_name: webb-wallpaper
    build: .
    ports:
      - "8080:8080"
    command: gunicorn --bind 0.0.0.0:8080 app:app
    labels:
      - com.centurylinklabs.watchtower.enable=false
      # Optional if you have homepage setup with docker
      - homepage.group=Applications
      - homepage.name=Webb Wallpaper
      - homepage.icon=/icons/webb-wallpaper.png
      - homepage.href=https://webb-wallpaper.tk
      - homepage.description=Generate wallpapers from images captured by JWST
      - homepage.ping=https://webb-wallpaper.tk
    restart: unless-stopped
networks:
  default:
    external: true
    name: nginxproxymanager
