version: '3.9'
services:
  webb-wallpaper:
    build: .
    ports:
      - "8080:8080"
    command: gunicorn --bind 0.0.0.0:8080 app:app
    labels:
      - com.centurylinklabs.watchtower.enable=false
    restart: unless-stopped
networks:
  default:
    external: true
    name: nginxproxymanager
