# From: https://towardsdatascience.com/the-easy-python-ci-cd-pipeline-using-docker-compose-and-github-actions-80498f47b341
name: Webb Wallpaper CI-CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Homelab
        uses: appleboy/ssh-action@master # Github actions ssh
        with:
          host: ${{ secrets.DOCKER_HOST }}
          username: ${{ secrets.DOCKER_USERNAME }}
          key: ${{ secrets.DOCKER_SSH_SECRET }}
          port: ${{ secrets.DOCKER_SSH_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull origin main
            docker compose down
            docker compose up --build -d --remove-orphans
            echo "Deleting old image(s)..."
            docker image prune -a -f
          # I really don't like that it removes all images not in use